### ISSUE TITLE
Godot4 support LUT

### ISSUE THREAD

**Issue by Darkinggq** [thiagoamendola/godot-color-lut-shader#9]
@thiagoamendola officialy Godot4.0 support LUT (addon can be forgotten) :)
![image](https://user-images.githubusercontent.com/17591539/98940971-e955b980-24fc-11eb-89ba-aa8934208b09.png)

now you are checking LUT for 4.0 good or bad 
https://github.com/godotengine/godot-proposals/issues/1382
-->pull https://github.com/godotengine/godot/pull/42761

**Comment by JapanYoshi** [comment]
@thiagoamendola Please close this issue as it isn’t a bug report or a feature request
